### ISSUE TITLE
error [AccessViolationException]

### ISSUE THREAD

**Issue by ali-hm** [VahidN/PersianBingCalendar#1]
سلام
آخرین ورژنی که ریلیز کردید خطا داره خطاش هم اینه
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Drawing.SafeNativeMethods.Gdip.GdipMeasureString(HandleRef graphics, String textString, Int32 length, HandleRef font, GPRECTF& layoutRect, HandleRef stringFormat, GPRECTF& boundingBox, Int32& codepointsFitted, Int32& linesFilled)
   at System.Drawing.Graphics.MeasureString(String text, Font font, SizeF layoutArea, StringFormat stringFormat)
   at System.Drawing.Graphics.MeasureString(String text, Font font)
   at PersianBingCalendar.Utils.DrawingExtensions.MeasureString(String text, Font f)
   at PersianBingCalendar.Core.PersianCalendarRenderer.getMaxCellSize(Int32 margin)
   at PersianBingCalendar.Core.PersianCalendarRenderer.setSizes()
   at PersianBingCalendar.Core.PersianCalendarRenderer.DrawThisMonthsCalendar()
   at PersianBingCalendar.Core.BingWallpaper.SetTodayWallpapaer()
   at PersianBingCalendar.Core.TaskRunner.RunTask()
   at PersianBingCalendar.Program.Main(String[] args)
یه مشکل دیگه هم داره توی 7 بک گراند رو نمیتونه ست کنه

**Comment by VahidN** [comment]
<div dir="rtl">

گاهي ممكن هست اين خطا را مشاهده كنيد ولي در كل برنامه كار مي‌كند و اين خطا مهم نيست
[Randomly occuring AccessViolationException in GDI+](http://stackoverflow.com/questions/5510115/randomly-occuring-accessviolationexception-in-gdi)

**Comment by ali-hm** [comment]
<div dir="rtl">
وقتی از ابتدا ورژن 1.2 را دانلود و اجرا کنید عکس ها دانلود شده اما زمانی که میخواهد بک گراند را بسازد فایل ساخته نشده و این خطا لاگ میشود و هیچ بک گراندی ست نمی شود.
در ضمن روی کامپیوتر من این خطا گاهی نیست و با هر بار اجرا بوجود می آید.
در مورد مشکل روی ویندوز 7 هم راهکاری دارید؟

**Comment by VahidN** [comment]
<div dir="rtl">
روي ويندوز 7 چه مشكلي دارد؟

**Comment by ali-hm** [comment]
فایل بک گراند ساخته میشه اما بک گراند ست نمیشود

**Comment by ali-hm** [comment]
با مشاهده سورس علت مشکل 
System.AccessViolationException 
رو متوجه شدم به خاطر
Dispose
شدن مموری مربوط به آبجکت بود که زمانی که از حالت 
using 
خارج بشه درست میشه و دیگه خطا نمیده

**Comment by ali-hm** [comment]
مشکل ویندوز 7 هم این بود که برای وال پیپر فرمت پی ان جی رو ساپورت نمیکنه اگه حالت ذخیره سازی رو ببری روی 
bmp
اون هم حل میشه
اگه اجازه بدی تغییرات رو کامیت کنم؟

**Comment by VahidN** [comment]
ممنون. در حال بررسي يك سري تغييرات روي رها سازي منابع فونت‌ها هستم. به زودي

**Comment by ali-hm** [comment]
پس کامیت نکنم؟

**Comment by VahidN** [comment]
نه. مشكل با حذف يوزنيگ نيست

**Comment by VahidN** [comment]
لطفا نگارش جديد را آزمايش كنيد
https://github.com/VahidN/PersianBingCalendar/releases/tag/V1.3

**Comment by ali-hm** [comment]
بله به نظر می رسد که مشکل حل شده است.
پیشنهاد دارم که یک آپشن باشد که عکس به صورت یک دوره زمانی مثلا ساعتی تغییر کند چون چندین عکس گرفته شده اما یکی از آخرین عکس استفاده می شود 
با تشکر

**Comment by VahidN** [comment]
<div dir="rtl">
اين تصاوير فقط روزي يكبار تغيير مي‌كنند و تغيير ساعتي آن‌ها حس تغيير را از بين مي‌برد؛ خصوصا زمانيكه روز عوض مي‌شود.
ولي مي‌شود براي آينده اين را هم اضافه كرد

**Comment by VahidN** [comment]
<div dir="rtl">
استفاده از بيت مپ الان مشكل فشرده سازي خودكار تصوير را توسط سيستم عامل ايجاد كرده كه ظاهر كار را خراب مي‌كند

**Comment by ali-hm** [comment]
می توان سیستم عامل را تشخیص داد و فقط برای ویندوز 7 از بیت مپ استفاده کرد و برای 10 از همان پی ان جی استفاده کرد
البته تا جایی که من میدانم برای بیت مپ در حالت 32 بیت فشرده سازی خاصی انجام نمیگیرد

**Comment by VahidN** [comment]
چون حجم تصوير بالا مي‌رود اين مشكل را درست مي‌كند
https://superuser.com/questions/507097/stop-windows-8-from-converting-wallpapers-to-low-quality-jpgs

**Comment by ali-hm** [comment]
پس چاره ای جز تشخیص سیستم عامل نیست

**Comment by ali-hm** [comment]
احتمالا بتوان با استفاده از ذخیره سازی جی پی جی و کیفیت 100 درصد مشکل را حل کرد. این حالت برای همه ویندوزها جواب می دهد.
من تغییر دادم مشکلی نداشت
`ImageCodecInfo jpgEncoder = GetEncoder(ImageFormat.Jpeg);
            System.Drawing.Imaging.Encoder myEncoder =
               System.Drawing.Imaging.Encoder.Quality;
            EncoderParameters myEncoderParameters = new EncoderParameters(1);
            EncoderParameter  myEncoderParameter = new EncoderParameter(myEncoder, 100L);
            myEncoderParameters.Param[0] = myEncoderParameter;
            
            using (var renderer = new PersianCalendarRenderer(imageFileName: imagePath)
            {
                Holidays = HolidaysReader.GetHolidays(),
                CopyrightText = lastDownalodResult.Copyright,
                TodayColor = Color.DarkRed,
                CopyrightFontName = "Tahoma",
                CopyrightFontSize = 19,
                CalendarFontFileName= "irsans.ttf",
                CalendarFontSize= 23
            })
            {
                using (var bitmap = renderer.DrawThisMonthsCalendar())
                {
                    const string wallpaperFileName = "_wallpaper.jpg";
                    var wallpaper = Path.Combine(dir, wallpaperFileName);
                    bitmap.Save(wallpaper, jpgEncoder,myEncoderParameters);

                    NativeMethods.SetWallpaper(wallpaper);
                    NativeMethods.SetLockScreenImage(wallpaper);
                }
            }`

در ضمن در آخرین نسخه 
Copyright
نمایش داده نمی شود

**Comment by VahidN** [comment]
متاسفانه كيفيت جي پي جي آن پايين هست
تشخيص سيستم عامل اضافه شد
https://github.com/VahidN/PersianBingCalendar/releases/tag/V1.4

**Comment by ali-hm** [comment]
اگه کیفیت جی پی جی رو 100 درصد میذاشتی کیفیت پایین نمی اومد
اما این راه حل هم جواب کار ما رو میده
ممنون
