### ISSUE TITLE
Archive downloaded images without modifying them

### ISSUE THREAD

**Issue by runo280** [VahidN/PersianBingCalendar#12]
اگر میشه برنامه عکس هایی که دانلود میکنه رو بدون تغییر هم توی یه پوشه ذخیره کنه
البته میتونه به صورت آپشن باشه که هر کسی مایل بود فعالش کنه
با تشکر

**Comment by VahidN** [comment]
<div dir="rtl">

به همين صورت هست
پوشه‌ي BingImages در كنار فايل اجرايي برنامه

**Comment by runo280** [comment]
درسته، منتها پسوند عکس ها جوری بود که بدون دقت معلوم نمیشد، بعد پیام شما یکیش رو تغییر دادم دیدم عکس هستن
متشکر
![image](https://user-images.githubusercontent.com/13608702/63640951-a8854100-c6bb-11e9-9382-090ce65cd50c.png)
