### ISSUE TITLE
آپشنی برای اضافه یا کم کردن به مقدار روز قمری

### ISSUE THREAD

**Issue by runo280** [VahidN/PersianBingCalendar#13]
از اونجایی که تاریخ شمسی فراگیر ویندوز برام کاربردی نیست، نمیتونم تاریخ قمری رو اصلاح کنم، لطفا یه آپشن بزارید که بشه یه عدد مثبت یا منفی رو جهت اضافه یا کم کردن از روز قمری قرار داد
با تشکر

**Comment by VahidN** [comment]
<div dir="rtl">

[در اينجا](https://github.com/VahidN/PersianBingCalendar#%D9%86%DA%A9%D8%A7%D8%AA-%D9%88-%D8%AA%D9%86%D8%B8%DB%8C%D9%85%D8%A7%D8%AA) توضيح دادم
قصد تغيير خاص ديگري هم در اين برنامه ندارم. اين برنامه در مرحله‌ي انجام شده قرار دارد
موفق باشيد
