### ISSUE TITLE
آبشنی برای غیرفعال کردن کپی رایت

### ISSUE THREAD

**Issue by xmha97** [VahidN/PersianBingCalendar#15]
سلام، لطفا آبشنی برای غیرفعال کردن کپی رایت اضافه کنید.
![image](https://user-images.githubusercontent.com/23485114/126051458-65da8ce7-b71d-48cc-9bf1-bd1d601ed99e.png)

**Comment by VahidN** [comment]
Added it via #https://github.com/VahidN/PersianBingCalendar/commit/24119e8019dbaf60f24300de65ea90b6ad297c17

**Comment by xmha97** [comment]
> 
> 
> Added it via #[24119e8](https://github.com/VahidN/PersianBingCalendar/commit/24119e8019dbaf60f24300de65ea90b6ad297c17)

Thanks <3

**Comment by xmha97** [comment]
@VahidN 
<div dir="rtl">

 ممنون اما نمیدونم چرا آخرین نسخه توسط ویندوز دیفندر ویروس شناسایی میشه و عملا اجازه‌ی استفاده رو نمیده!

![image](https://user-images.githubusercontent.com/23485114/126087036-c669c7cd-b92a-495d-bea1-8f69e691028f.png)

پیشنهاد میشه به جای استفاده از کلمه‌ی Copyright از کلمه‌ی Information استفاده کنید.

**Comment by VahidN** [comment]
<div dir="rtl">

پيشنهاد ميشه برنامه‌ها رو از داخل پوشه‌ي Temp اجرا نكنيد. اين پوشه و مسير آن توسط ويندوز محافظت شده‌است
[همچنين اين بسته توسط تمام ويروس ياب‌ها تميز تشخيص داده شد](https://www.virustotal.com/gui/url/df06588bf9afddf71bfaa9649ace69f3f813c6ee64b8bc9dd77456ca64fed46c/detection)
