### ISSUE TITLE
آبشنی برای تاریک‌کردن تصویر پس‌زمینه

### ISSUE THREAD

**Issue by xmha97** [VahidN/PersianBingCalendar#16]
<div dir="rtl">

# مسئله:
همانطوری که میدانید، پس‌زمینه‌های بینگ اکثرا طبیعت است و به علت روشنایی زیاد این تصاویر در شب قابل استفاده نیستند.
همچنین در برخی از پس‌زمینه‌های شلوغ، تقویم به راحتی قابل خواندن نیست.

# راه‌حل:
من می‌خواهم ویژگی‌ای را اضافه کنید که بتوانم تصویر را کمی تاریک کنم.

# نحوه‌ی پیاده‌سازی:
پیاده سازی این ویژگی اصلا سخت نیست فقط کافیه که یک مستطیل به صورت ترنسپرنت بر کل عکس ترسیم شود:
<div dir="ltr">

```
myGraphics.FillRectangle(new SolidBrush(Color.FromArgb(DarkValue, Color.Black)), new Rectangle(new Point(0, 0), OutputImage.Size));
```
<div dir="rtl">

به هر حال می‌توانید از این پروژه هم استفاده کنید: [ImageDarker.zip](https://github.com/VahidN/PersianBingCalendar/files/6837161/ImageDarker.zip)
![image](https://user-images.githubusercontent.com/23485114/126086298-ff9724d6-06fd-4471-a6de-309d670ebfcd.png)

**Comment by VahidN** [comment]
<div dir="rtl">

چنين قصدي را ندارم

**Comment by xmha97** [comment]
اوکی، اگه پول ریکوئست بدم مرج می‌کنید؟
