### ISSUE TITLE
Anti Virus Alert for find High risk Application

### ISSUE THREAD

**Issue by ekhtiari** [VahidN/PersianBingCalendar#17]
Hi Dear Vahid.
in last day Windows Security Application show message that find a Threat program and delete your exe file.
I Check PersianBingCalendar.exe with Virus Total Site and receive some alert message . 

https://www.virustotal.com/gui/file/93f95807331ec6b48eb50672dcf0ecfe497298280f1abe07cba3efe9000f80ce 

can you help me why Windows Security and some Anti Virus recognize this application as a threat ? 
it was happen last month and Windows Security remove the exe file

**Comment by VahidN** [comment]
> can you help me why Windows Security and some Anti Virus recognize this application as a threat ?

- I don't know. Maybe it's a [false positive](https://en.wikipedia.org/wiki/False_positives_and_false_negatives) and can be ignored. Probably some malwares are using the same `run on startup` or `add a new windows task` features.
- You can always download the source code and build it yourself.
- Also [you can add exclusions](https://support.microsoft.com/en-us/windows/add-an-exclusion-to-windows-security-811816c0-4dfd-af4a-47e4-c301afe13b26) to windows defender.
