### ISSUE TITLE
Windows defender detect the exe file as Trojan:Win32/Wacatac.H!ml

### ISSUE THREAD

**Issue by ali-hm** [VahidN/PersianBingCalendar#18]
# Summary of the issue
Windows defender detect the exe file as Trojan:Win32/Wacatac.H!ml and quarantine it.

## Environment
Windows 10
```
The in-use version: 2.3
Operating system: Windows 10

**Comment by VahidN** [comment]
Unfortunately I can't do anything about it. [More info](https://github.com/VahidN/PersianBingCalendar/issues/17#issuecomment-1209183805).
