### ISSUE TITLE
عکس خراب دانلود میشود

### ISSUE THREAD

**Issue by xmha97** [VahidN/PersianBingCalendar#2]
با سلام
عکس بعصی اوقات خراب دانلود میشود
``
![screenshot 54](https://cloud.githubusercontent.com/assets/23485114/24631040/2f82c3aa-18d4-11e7-9885-f3c690336f2a.png)

**Comment by VahidN** [comment]
اين مورد بيشتر به خط اينترنت شما مرتبط است و سرعت آن و كيفيت آن

**Comment by VahidN** [comment]
مقدار تايم آوت افزايش داده شد
https://github.com/VahidN/PersianBingCalendar/releases

**Comment by xmha97** [comment]
ممنون
