### ISSUE TITLE
ایجاد فایل نصب برای برنامه

### ISSUE THREAD

**Issue by xmha97** [VahidN/PersianBingCalendar#3]
لطفا برای این برنامه فایل نصب بسازید تا راحت تر بشود از آن استفاده کرد.

**Comment by VahidN** [comment]
نيازي به اين كار نيست. برنامه بدون فايل نصبي بدون مشكل كار مي‌كند و **پرتابل** (قابل حمل) است

**Comment by nxp1024** [comment]
برنامه هایی پرتابل منتشر میشن که زیاد ازشون استفاده نمیشه مثل برنامه Rufus که هر یک سال یک بار باهاش ویندوز رو بوت میکنیم.

اما این برنامه هر یک ساعت اجرا میشه
به دلیل این که برنامه مسیر مشخصی ندارد ممکن است در پوشه برنامه تغییر نام یا حذف شود و از کار بیوفتد.

**Comment by nxp1024** [comment]
برنامه هایی پرتابل منتشر میشن که زیاد ازشون استفاده نمیشه مثل برنامه
Rufus
که هر یک سال یک بار باهاش ویندوز رو بوت میکنیم.


اما این برنامه هر یک ساعت اجرا میشه
به دلیل این که برنامه مسیر مشخصی ندارد ممکن است در پوشه برنامه تغییر نام یا حذف شود و از کار بیوفتد.

**Comment by xmha97** [comment]
برنامه هایی پرتابل منتشر میشن که زیاد ازشون استفاده نمیشه مثل برنامه
Rufus
که هر یک سال یک بار باهاش ویندوز رو بوت میکنیم


اما این برنامه هر یک ساعت اجرا میشه
به دلیل این که برنامه مسیر مشخصی ندارد ممکن است در پوشه برنامه تغییر نام یا حذف شود و از کار بیوفتد

**Comment by VahidN** [comment]
<div dir="rtl">
از اين لحاظ مشكلي ندارد. در هر بار اجرا، مسير وظيفه‌ي اضافه شده‌ي به ويندوز به صورت خودكار توسط برنامه به روز رساني مي‌شود. بنابراين اگر پوشه را تغيير داديد، تنها كاري كه بايد انجام دهيد، اجراي دستي و مجدد برنامه است و بعد از آن سر ساعت كار مي‌كند

**Comment by xmha97** [comment]
ممنون بخاطر این همه دقت در ساخت این نرم افزار
