### ISSUE TITLE
تداخل در نمایش تاریخ قمری

### ISSUE THREAD

**Issue by skhalil89** [VahidN/PersianBingCalendar#4]
سلام. ممنون از ایده جالب و قشنگتون.
اما امروز من برنامه رو گرفتم و تاریخ قمری رو اشتباه نشون میده. یه روز جلو تره.
ممنون میشم اصلاح کنید.
یه پیشنهاد هم داشتم که فونت مناسبت ها کمی کوچکتر بشه 

![bug](https://cloud.githubusercontent.com/assets/6417734/24826171/1433f00a-1c45-11e7-9fdf-47f136547fcc.png)

**Comment by VahidN** [comment]
<div dir="rtl">

در مورد تاريخ قمري ويندوز [در اينجا](http://www.dotnettips.info/post/2534) توضيح دادم

**Comment by mohsenrbb** [comment]
با تغییر این قسمت هم مشکل حل نشد

**Comment by VahidN** [comment]
<div dir="rtl">

اين مشكل در نگارش جديد برطرف شد
https://github.com/VahidN/PersianBingCalendar/releases
همچنين تنظيم اندازه فونت هم به فايل كانفيگ آن اضافه شد
