### ISSUE TITLE
عدم نمایش مناسبت‌های گذشته

### ISSUE THREAD

**Issue by mohsenrbb** [VahidN/PersianBingCalendar#5]
با سلام
مناسبت‌هایی که تاریخ آن‌ها عبور کرده نمایش داده نمی‌شود

**Comment by VahidN** [comment]
<div dir="rtl">
بله. به همين صورت تنظيم شده‌است (گذشته، گذشته)

**Comment by mohsenrbb** [comment]
درسته که گذشته گذشته
ولی خب شاید کسی بخواد بدونه که روز پدر که گذشته چند شنبه بود چندم بوده
حداقل میشد به عنوان یه امکان اختیاری بهش فکر کرد

**Comment by VahidN** [comment]
<div dir="rtl">

تنظيم اين مورد به فايل كانفيگ برنامه تحت عنوان ShowPastHolidays اضافه شد
https://github.com/VahidN/PersianBingCalendar/releases
