### ISSUE TITLE
there is a Bug in getImage Function

### ISSUE THREAD

**Issue by ali-hm** [VahidN/PersianBingCalendar#7]
Hi,
in getImage function there is a bug in this line
if (!File.Exists(xmlFile))
            {
                xmlFile = $"{image.Split('_').First()}.xml";
            }
if the image path contains _ character in the folders it does not work as you want.

**Comment by VahidN** [comment]
The Bing images always contain `_` character. Take a look at the .xml files, you will see names like `TulipFestival_EN-US8173850763_1366x768.jpg`. And the program takes the `TulipFestival` here as the xml file name.

**Comment by ali-hm** [comment]
I know about the fileNames. but this method works with full path such as d:\test_dir\BingImages\TulipFestival_EN-US8173850763_1366x768.jpg
in this occasion it will not work correctly.

**Comment by VahidN** [comment]
No. [It uses the file name, not the full path](https://github.com/VahidN/PersianBingCalendar/blob/master/PersianBingCalendar/Core/BingImagesDownloader.cs#L58).

**Comment by ali-hm** [comment]
i see that in debug. it uses fullpath 
var image = lastImage.FullName;
and it has this bug so it is yours to decide whether to fix it or not. I have fixed it in my local repo. 
your mentioned link is in downloadImage method. this bug is in getImage method

**Comment by VahidN** [comment]
[It's fixed now](https://github.com/VahidN/PersianBingCalendar/releases).

**Comment by ali-hm** [comment]
ok thanks.
